# All relevant modules for us can be found here
---
- name: sample book
  hosts: traffic_generator
  remote_user: root
  become: true # privilage escalation
  tasks: 
    - name: install httpd
      yum: 
          name: httpd
          state: latest
    - name: run httpd
      service: 
            name: httpd
            state: started
    - name: create content
      copy: 
          content: "Congrats on installing ansible"
          dest: /var/www/html/index.html 